In [ ]:
# Logistic Regression Model for Telco Churn
#  Modelling
# This notebook builds a simple churn prediction model using engineered SQL features

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
import os
os.getcwd()

In [ ]:
df = pd.read_csv("c:\\Users\\osegh\\OneDrive\\Desktop\\telco-churn-analytics\\data\\clean\\clean_telco_churn.csv", sep=';')

In [ ]:
df.head()

In [ ]:
features = [
    'tenure',
    'MonthlyCharges',
    'TotalCharges',
    'SeniorCitizenFlag',
    'HasPartnerFlag',
    'ChurnFlag',
    'ContractCategory',
    'PaymentCategory',
    'TenureGroup'
]

In [ ]:
df.columns

In [ ]:
df.columns.tolist()

In [ ]:
df.columns.tolist()

In [ ]:
df.columns = df.columns.str.replace('"', '').str.strip()

In [ ]:
df.columns.tolist()

In [ ]:
df = pd.get_dummies(df, columns=['ContractCategory', 'PaymentCategory', 'TenureGroup'], drop_first=True)

In [ ]:
df.head()

In [ ]:
X = df.drop(['Churn', 'ChurnFlag', 'customerID'], axis=1)
y = df['ChurnFlag']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

In [ ]:
df.dtypes

In [ ]:
df = pd.get_dummies(df, columns=['ContractCategory', 'PaymentCategory', 'TenureGroup'], drop_first=True)

In [ ]:
df.columns.tolist()

In [ ]:
df = pd.get_dummies(df, columns=['ContractCategory', 'PaymentCategory', 'TenureGroup'], drop_first=True)

In [ ]:
df = pd.read_csv("c:\\Users\\osegh\\OneDrive\\Desktop\\telco-churn-analytics\\data\\clean\\clean_telco_churn.csv", sep=None, engine="python")
df.head()

In [ ]:
with open("c:\\Users\\osegh\\OneDrive\\Desktop\\telco-churn-analytics\\data\\clean\\clean_telco_churn.csv", "r") as f:
    for i in range(3):
        print(repr(f.readline()))

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
df = pd.read_csv("c:\\Users\\osegh\\OneDrive\\Desktop\\telco-churn-analytics\\data\\clean\\clean_telco_churn.csv")

In [4]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'TenureGroup',
 'ChurnFlag',
 'ContractCategory',
 'PaymentCategory',
 'SeniorCitizenFlag',
 'HasPartnerFlag']

In [5]:
df.columns = df.columns.str.replace('"', '').str.strip()

In [6]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'TenureGroup',
 'ChurnFlag',
 'ContractCategory',
 'PaymentCategory',
 'SeniorCitizenFlag',
 'HasPartnerFlag']

In [7]:
df = pd.get_dummies(
    df,
    columns=['ContractCategory', 'PaymentCategory', 'TenureGroup'],
    drop_first=True
)

In [8]:
X = df.drop(['Churn', 'ChurnFlag', 'customerID'], axis=1)
y = df['ChurnFlag']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Female'

In [11]:
df.dtypes[df.dtypes == "object"]

customerID          object
gender              object
Partner             object
Dependents          object
PhoneService        object
MultipleLines       object
InternetService     object
OnlineSecurity      object
OnlineBackup        object
DeviceProtection    object
TechSupport         object
StreamingTV         object
StreamingMovies     object
Contract            object
PaperlessBilling    object
PaymentMethod       object
Churn               object
dtype: object

In [12]:
X = df[[
    'tenure',
    'MonthlyCharges',
    'TotalCharges',
    'SeniorCitizenFlag',
    'HasPartnerFlag',
    'ContractCategory',
    'PaymentCategory',
    'TenureGroup'
]]

KeyError: "['ContractCategory', 'PaymentCategory', 'TenureGroup'] not in index"

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("c:\\Users\\osegh\\OneDrive\\Desktop\\telco-churn-analytics\\data\\clean\\clean_telco_churn.csv")

In [3]:
df.columns = df.columns.str.replace('"', '').str.strip()

In [4]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'TenureGroup',
 'ChurnFlag',
 'ContractCategory',
 'PaymentCategory',
 'SeniorCitizenFlag',
 'HasPartnerFlag']

In [5]:
df = pd.get_dummies(
    df,
    columns=['ContractCategory', 'PaymentCategory', 'TenureGroup'],
    drop_first=True
)

In [6]:
y = df['ChurnFlag']

X = df.drop(['Churn', 'ChurnFlag', 'customerID'], axis=1)

In [7]:
X.dtypes

gender                          object
SeniorCitizen                    int64
Partner                         object
Dependents                      object
tenure                           int64
PhoneService                    object
MultipleLines                   object
InternetService                 object
OnlineSecurity                  object
OnlineBackup                    object
DeviceProtection                object
TechSupport                     object
StreamingTV                     object
StreamingMovies                 object
Contract                        object
PaperlessBilling                object
PaymentMethod                   object
MonthlyCharges                 float64
TotalCharges                   float64
SeniorCitizenFlag                int64
HasPartnerFlag                   int64
ContractCategory_Short-term       bool
PaymentCategory_Electronic        bool
PaymentCategory_Other             bool
TenureGroup_13-24                 bool
TenureGroup_25-48                 bool
TenureGroup_49+                   bool
dtype: object

In [8]:
print(df.columns.tolist())

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn', 'ChurnFlag', 'SeniorCitizenFlag', 'HasPartnerFlag', 'ContractCategory_Short-term', 'PaymentCategory_Electronic', 'PaymentCategory_Other', 'TenureGroup_13-24', 'TenureGroup_25-48', 'TenureGroup_49+']

In [9]:
y = df['ChurnFlag']

X = df.drop([
    'Churn',
    'ChurnFlag',
    'customerID',
    'gender',
    'Partner',
    'Dependents',
    'PhoneService',
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'Contract',
    'PaperlessBilling',
    'PaymentMethod'
], axis=1)

In [10]:
X.dtypes

SeniorCitizen                    int64
tenure                           int64
MonthlyCharges                 float64
TotalCharges                   float64
SeniorCitizenFlag                int64
HasPartnerFlag                   int64
ContractCategory_Short-term       bool
PaymentCategory_Electronic        bool
PaymentCategory_Other             bool
TenureGroup_13-24                 bool
TenureGroup_25-48                 bool
TenureGroup_49+                   bool
dtype: object

In [11]:
df = df.astype({col: 'int' for col in df.select_dtypes('bool').columns})

In [12]:
df.dtypes

customerID                      object
gender                          object
SeniorCitizen                    int64
Partner                         object
Dependents                      object
tenure                           int64
PhoneService                    object
MultipleLines                   object
InternetService                 object
OnlineSecurity                  object
OnlineBackup                    object
DeviceProtection                object
TechSupport                     object
StreamingTV                     object
StreamingMovies                 object
Contract                        object
PaperlessBilling                object
PaymentMethod                   object
MonthlyCharges                 float64
TotalCharges                   float64
Churn                           object
ChurnFlag                        int64
SeniorCitizenFlag                int64
HasPartnerFlag                   int64
ContractCategory_Short-term      int64
PaymentCategory_Electronic       int64
PaymentCategory_Other            int64
TenureGroup_13-24                int64
TenureGroup_25-48                int64
TenureGroup_49+                  int64
dtype: object

In [13]:
y = df['ChurnFlag']

X = df.drop([
    'Churn',
    'ChurnFlag',
    'customerID',
    'gender',
    'Partner',
    'Dependents',
    'PhoneService',
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'Contract',
    'PaperlessBilling',
    'PaymentMethod'
], axis=1)

In [14]:
X.dtypes

SeniorCitizen                    int64
tenure                           int64
MonthlyCharges                 float64
TotalCharges                   float64
SeniorCitizenFlag                int64
HasPartnerFlag                   int64
ContractCategory_Short-term      int64
PaymentCategory_Electronic       int64
PaymentCategory_Other            int64
TenureGroup_13-24                int64
TenureGroup_25-48                int64
TenureGroup_49+                  int64
dtype: object

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

c:\Users\osegh\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1033
           1       0.62      0.47      0.53       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.69      1407
weighted avg       0.77      0.78      0.77      1407

[[925 108]
 [200 174]]

In [17]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

importance

                        Feature  Coefficient
6   ContractCategory_Short-term     1.212637
11              TenureGroup_49+     0.960540
7    PaymentCategory_Electronic     0.476122
0                 SeniorCitizen     0.251728
4             SeniorCitizenFlag     0.251728
10            TenureGroup_25-48     0.232090
2                MonthlyCharges     0.023805
3                  TotalCharges     0.000119
5                HasPartnerFlag    -0.030063
1                        tenure    -0.062695
8         PaymentCategory_Other    -0.126914
9             TenureGroup_13-24    -0.290754

In [18]:
import pandas as pd

coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

coef_df

                        Feature  Coefficient
6   ContractCategory_Short-term     1.212637
11              TenureGroup_49+     0.960540
7    PaymentCategory_Electronic     0.476122
0                 SeniorCitizen     0.251728
4             SeniorCitizenFlag     0.251728
10            TenureGroup_25-48     0.232090
2                MonthlyCharges     0.023805
3                  TotalCharges     0.000119
5                HasPartnerFlag    -0.030063
1                        tenure    -0.062695
8         PaymentCategory_Other    -0.126914
9             TenureGroup_13-24    -0.290754

In [19]:
coef_df

                        Feature  Coefficient
6   ContractCategory_Short-term     1.212637
11              TenureGroup_49+     0.960540
7    PaymentCategory_Electronic     0.476122
0                 SeniorCitizen     0.251728
4             SeniorCitizenFlag     0.251728
10            TenureGroup_25-48     0.232090
2                MonthlyCharges     0.023805
3                  TotalCharges     0.000119
5                HasPartnerFlag    -0.030063
1                        tenure    -0.062695
8         PaymentCategory_Other    -0.126914
9             TenureGroup_13-24    -0.290754

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1033
           1       0.62      0.47      0.53       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.69      1407
weighted avg       0.77      0.78      0.77      1407

[[925 108]
 [200 174]]